.defs:
  - &debug { level: DEBUG }
  - &info { level: INFO }
  - &warning { level: WARNING }
  - &error { level: ERROR }
  - &critical { level: CRITICAL }
# https://docs.python.org/3/library/logging.config.html#logging-config-dictschema
version: 1
loggers:
  root: *info

  # These are quite noisy.
  reacton: *warning
